apiVersion: v1
kind: Secret
metadata:
  name: backend
type: Opaque
data:
  db_url: cG9zdGdyZXM6Ly9hZG1pbjphZG1pbjEyM0Bnby1wb3N0Z3Jlc3FsLWhsLnBvc3RncmVzLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvY3J1ZD9zc2xtb2RlPWRpc2FibGU=
  log_level: ZGVidWc=
