apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  namespace: "{{ .Values.namespace }}"
  labels: {{- toYaml .Values.selectorLabels | nindent 4 }}
spec:
  type: "{{ .Values.service.type }}"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector: {{- toYaml .Values.selectorLabels | nindent 4 }}
